create table if not exists public.product_search_sync_events (
  id bigint generated by default as identity primary key,
  product_id uuid not null,
  operation text not null check (operation in ('upsert', 'delete')),
  status text not null default 'pending' check (status in ('pending', 'processing', 'synced', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  processed_at timestamptz
);

comment on table public.product_search_sync_events is 'Server-owned queue for syncing product changes from Postgres into the external Typesense product index.';
comment on column public.product_search_sync_events.product_id is 'Product id to sync. Kept without a foreign key so delete events can be retained after product deletion.';
comment on column public.product_search_sync_events.operation is 'upsert indexes the latest product document; delete removes it from Typesense.';

create index if not exists idx_product_search_sync_events_status_created
  on public.product_search_sync_events (status, created_at);

create index if not exists idx_product_search_sync_events_product_created
  on public.product_search_sync_events (product_id, created_at desc);

alter table public.product_search_sync_events enable row level security;

create policy "Admins can read product search sync events"
  on public.product_search_sync_events
  for select
  to authenticated
  using (public.is_admin());

create policy "Admins can update product search sync events"
  on public.product_search_sync_events
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create or replace function public.touch_product_search_sync_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_product_search_sync_event on public.product_search_sync_events;
create trigger trg_touch_product_search_sync_event
before update on public.product_search_sync_events
for each row execute function public.touch_product_search_sync_event();

create or replace function public.enqueue_product_search_sync()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    insert into public.product_search_sync_events (product_id, operation)
    values (old.id, 'delete');
    return old;
  end if;

  insert into public.product_search_sync_events (product_id, operation)
  values (new.id, 'upsert');
  return new;
end;
$$;

drop trigger if exists trg_enqueue_product_search_sync on public.products;
create trigger trg_enqueue_product_search_sync
after insert or update or delete on public.products
for each row execute function public.enqueue_product_search_sync();

revoke execute on function public.enqueue_product_search_sync() from anon, authenticated;
revoke execute on function public.touch_product_search_sync_event() from anon, authenticated;
revoke execute on function public.enqueue_product_search_sync() from public;
revoke execute on function public.touch_product_search_sync_event() from public;

comment on function public.enqueue_product_search_sync() is 'Trigger-only helper; direct API execution is revoked from anon/authenticated roles.';
comment on function public.touch_product_search_sync_event() is 'Trigger-only helper; direct API execution is revoked from anon/authenticated roles.';

insert into public.product_search_sync_events (product_id, operation)
select p.id, 'upsert'
from public.products p
where p.status = 'active'
  and not exists (
    select 1
    from public.product_search_sync_events e
    where e.product_id = p.id
      and e.operation = 'upsert'
      and e.status in ('pending', 'processing', 'synced')
  );
